import { Character } from "@lib/constants/characters";

export const mockCharacter: Character = {
  id: "1",
  name: "Harry Potter",
  alternate_names: ["The Boy Who Lived", "The Chosen One"],
  species: "human",
  gender: "male",
  house: "Gryffindor",
  dateOfBirth: "31-07-1980",
  yearOfBirth: 1980,
  wizard: true,
  ancestry: "half-blood",
  eyeColour: "green",
  hairColour: "black",
  wand: { wood: "holly", core: "phoenix feather", length: 11 },
  patronus: "stag",
  hogwartsStudent: true,
  hogwartsStaff: false,
  actor: "Daniel Radcliffe",
  alternate_actors: [],
  alive: true,
  image: "https://example.com/harry.jpg",
};

export const mockCharacters: Character[] = [
  mockCharacter,
  {
    id: "2",
    name: "Hermione Granger",
    species: "human",
    gender: "female",
    house: "Gryffindor",
    wizard: true,
    ancestry: "muggleborn",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Emma Watson",
    alive: true,
    image: "https://example.com/hermione.jpg",
  },
  {
    id: "3",
    name: "Severus Snape",
    species: "human",
    gender: "male",
    house: "Slytherin",
    wizard: true,
    ancestry: "half-blood",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Alan Rickman",
    alive: false,
    image: "https://example.com/snape.jpg",
  },
  {
    id: "4",
    name: "Dobby",
    species: "house-elf",
    gender: "male",
    wizard: false,
    hogwartsStudent: false,
    hogwartsStaff: false,
    alive: false,
  },
];
