/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as charactersIndexRouteImport } from './routes/(characters)/index'

const charactersIndexRoute = charactersIndexRouteImport.update({
  id: '/(characters)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof charactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof charactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(characters)/': typeof charactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(characters)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  charactersIndexRoute: typeof charactersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(characters)/': {
      id: '/(characters)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof charactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  charactersIndexRoute: charactersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
