/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as charactersIndexRouteImport } from './routes/(characters)/index'
import { Route as charactersCharacterNameRouteImport } from './routes/(characters)/$characterName'

const charactersIndexRoute = charactersIndexRouteImport.update({
  id: '/(characters)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const charactersCharacterNameRoute = charactersCharacterNameRouteImport.update({
  id: '/(characters)/$characterName',
  path: '/$characterName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$characterName': typeof charactersCharacterNameRoute
  '/': typeof charactersIndexRoute
}
export interface FileRoutesByTo {
  '/$characterName': typeof charactersCharacterNameRoute
  '/': typeof charactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(characters)/$characterName': typeof charactersCharacterNameRoute
  '/(characters)/': typeof charactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$characterName' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$characterName' | '/'
  id: '__root__' | '/(characters)/$characterName' | '/(characters)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  charactersCharacterNameRoute: typeof charactersCharacterNameRoute
  charactersIndexRoute: typeof charactersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(characters)/': {
      id: '/(characters)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof charactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(characters)/$characterName': {
      id: '/(characters)/$characterName'
      path: '/$characterName'
      fullPath: '/$characterName'
      preLoaderRoute: typeof charactersCharacterNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  charactersCharacterNameRoute: charactersCharacterNameRoute,
  charactersIndexRoute: charactersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
